### ISSUE TITLE
Complexity of 'Combination' functions.

### ISSUE THREAD

**Issue by archblob** [haskell/critbit#49]
From what I understand, and if I'm not mistaken, the complexity of union is O(n*log m) where n is the size of the second map and m the size of the first one.
Can't we do better ? I've tried to implement the difference function and I have not found a way to do it better.

**Comment by isturdy** [comment]
I was just thinking of our complexities in general--because we cannot guarantee that CritBit trees are balanced, the worst-case complexity of anything that involves traversing the tree to an arbitrary leaf should be _O(min(m,n))_ for a dataset of _n_ elements with longest key _m_ bits, not the _O(log n)_ for the BBT (with the caveat that most sets will be approximately balanced, so the _O(log n)_ is a reasonable guess for actual behaviour).

That said, I put a fair amount of thought into `intersect` last week, without any great revelations. In general, these functions seem to suffer from the lack of a representative key at `Internal` nodes, making efficient comparison of two nodes (rather than a node and a key) difficult.

**Comment by archblob** [comment]
I don't know about _difficult_ , I don't see a way to decide direction based solely on the information stored in the compared `Internal` nodes.
This is as far as I got with `difference` , simply comparing it with the containers function passes the test most of the time, because I written crappy tests :-P, but once in a while this comes up:
`KV {fromKV = [("a",0),("Y",1)]}`
`KV {fromKV = [("",0),("Y",1)]}`

**Comment by isturdy** [comment]
Impossible only from the information in the nodes (you cannot handle trees with different prefixes up to a node), but certainly possible in general. I banged on improving the union functions longer than it should have taken yesterday; the key (as kgeorgiy found, with greater success) seems to be to use a traversal to a leaf (any will do, since by definition all leaves beneath a node share a prefix up to the critical bit of that node) to determine whether where to add a branch.

**Comment by archblob** [comment]
I was not referring to the general case of course. I have been pretty much slowly moving through the research papers cited as reference in the Map and IntMap implementations of merges because the code in the package is very hard to read and the papers are a delight.  That said, very nice job @kgeorgiy , maybe you can implement a generalised mergeWithKey as seen in the containers pacakge?

**Comment by kgeorgiy** [comment]
Wow! Now I know the name of that function (`mergeWithKey`)! Thank you.

Actually I've alredy implemented that function in the [set](https://github.com/kgeorgiy/critbit/tree/set) branch: https://github.com/kgeorgiy/critbit/compare/master...set

Unfortunately, this unification in case of CritBit trees leads to slow performance. In the `intersection` and `difference` we never have to create a new `Internal` node, only replacements for existing `Internal` nodes. In the `union` we should always check for the necessity of the new `Internal` node via comparing the keys. Actually my implementation of `intersection` and `difference` should run in _O((n+m)k)_, while `union` takes  _O((n+m)k^2)_ time, where _k_ is the length of the longest key.

It is possible to implement all three functions in _O(n+m+K)_ where _K_ is total length of all strings, but it requires redesign of the all recursive functions in the `CritBit` package.
