### ISSUE TITLE
Bugs in `split` and `splitLookup`

### ISSUE THREAD

**Issue by kgeorgiy** [haskell/critbit#74]
Current imlementation of `split` and `splitLookup` is invalid.

Call `split "bb" $ fromList [("aa", 1), ("ac", 2), ("ad", 3)]` returns `(fromList [("aa",1),("ac",2)],fromList [("ad",3)])` instead of `(fromList [("aa",1),("ac",2), ("ad",3)],fromList [])`. 

The same arguments demonstrate bug in `splitLookup`.

**Comment by kgeorgiy** [comment]
Possible fix: `split` and `splitLookup` should be reimplemented with rewalk, as in `insertWithKey`.

I'm going to include fix in the #69 pull request. Some new functions make this implementation pretty simple.

**Comment by archblob** [comment]
I had a discussion with @isturdy when we both implemented  ''' splitLookup ''' and  ''' split '''  and we both seem to have missed this. Anyway i already have split and splitLookup implemented using rewalk from my pull request back then.
In order to not duplicate efforts i can send another pull request and fix this, that is if you haven't already written the functions or if you don't want to write them. I will wait for your answer.
See our discussion here #31 and here #40 .

**Comment by kgeorgiy** [comment]
I've already fixed them in my code.
Now I'm running performance test for complete pull request.

**Comment by kgeorgiy** [comment]
Pushed fix to this problem along with refactorings.

The problem with implementation is solved, but we still have a problem with tests. Current test set does not detects this bug. Surely, we can add specific hand-made test case for this bug, but this approach is not not constructive. Actually, we should fix generator of test tree. Unfortunately, I don't see a generic way to do this.

**Comment by kgeorgiy** [comment]
Tests was invalid in two ways:
- `t_split_*` used type-providing (empty) key as actual key
- `t_split_*` used instead of `t_splitLookup_*`

These tests fail now.
