### ISSUE TITLE
Generalize Core.delete to updateWithKey

### ISSUE THREAD

**Issue by bcdarwin** [haskell/critbit#9]
In the definition of `delete`,

```
go (Leaf lk _) cont
   | k == lk = cont Empty
```

becomes

```
go (Leaf lk lv) cont
  | k == lk = case f k lv of
                Just lv' -> cont (Leaf lk lv')
                Nothing  -> cont Empty
```

since - unlike with Data.Map - we don't rebalance the tree on a deletion. Then `delete = updateWithKey (const (const Nothing))`.

Hopefully this isn't too hard on GHC. I'll look at this unless someone else is interested.

**Comment by bos** [comment]
Looks reasonable. Just make sure that the before/after performance of `delete` remains unchanged, please. (And maybe write an explicit lambda instead of nested `const`, because you'll melt this poor reader's brain.)

**Comment by rbobrowicz** [comment]
I'd like to do this since I was already planning on implementing the `adjust` function which should also probably be implemented in terms of `updateWithKey`. I've done some preliminary benchmarks and the performance difference of the two implementations of `delete` seems to be negligible (within one percent of each other), so it looks like GHC is smart enough to handle this case properly. 

EDIT: Nevermind, it looks like bcdarwin submitted a pull request right as I was typing this.
